# Generated by Django 5.2.11 on 2026-02-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Toggle to enable or disable the sale status and badge.'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_badge_text',
            field=models.CharField(blank=True, default='Sale!', help_text="Custom text for the sale badge (e.g., '20% OFF', 'Clearance').", max_length=50),
        ),
    ]
